#!/bin/bash -e

path="$1"
id=${2:-$PPID}

if [[ -z "$path" ]];then
  title=addRecentFile sendNotification "empty request"
fi

in_reg="$(mktmpVar)"
echo "recent_files" > "$in_reg"
echo -n "$path" >> "$in_reg"
request flat-cache add "$in_reg"

in_reg="$(mktmpVar)"
echo "recent_files" > "$in_reg"
echo "$path" >> "$in_reg"
echo -n "$id" >> "$in_reg"
request flat-cache addTemporary "$in_reg"


