#!/bin/bash

let curr_row=`cat /tmp/nav/row`
if [[ ! $curr_row -eq 0 ]];then
  ((curr_row--))
  #listing=$(list2 `cat /tmp/nav/path` "alpha" | awk '{print $10)')
  listing=$(eval "$FZF_DEFAULT_COMMAND" | awk '{print $1}' | perl -pe 's/\e([^\[\]]|\[.*?[a-zA-Z]|\].*?\a)//g')
  listing="\n $listing"
  echo "$listing" >> /tmp/deb
  listing_arr=($listing)
  echo ${listing_arr[$curr_row]} > /tmp/nav/cursor_at
  echo $curr_row > /tmp/nav/row
  updatePreview
fi

