#!/bin/bash -e

id="$1"


abs_dir=$(getAbsDir "$id")
if [[ -z "$abs_dir"  ]];then
  echo "not force deleting /* directory"
  exit 1
fi

arg=$(getArg "$id" "$2")
if [[ -z "$arg" || "$arg" == *"total"* ]];then
  exit 0
fi
path="$abs_dir/$arg"

#echo $arg | awk '{print $1}' >> /tmp/deb
#echo $path >> /tmp/deb

if [[ -L "$path" ]];then
  rm "$path"
elif [[ -e "$path" ]];then
    #echo deleting $arg $(du -sh "$path" 2> "$HOME"/null | awk '{print $1}') > $FILE_WARP_TMP_PATH/$id/console
    rm -rf "$path" &
    wait=.1
    while [[ -e "$path" ]];do
      echo deleting $arg $(du -sh "$trash/$arg" 2> "$HOME"/null | awk '{print $1}') > $FILE_WARP_TMP_PATH/$id/console
      if [[ -e "$trash/$arg" ]];then
        sleep "$wait"
      fi
      . incWait
    done
fi

