#!/bin/bash -e

start="$1"
mode=${2:-normal}
from_ide=${3:-0}
called_from_index="$4"
if [[ $from_ide == 1 ]];then
  export id=0
else
  #export id=$PPID
  export id=$$
fi
mkdir -p "$FILE_WARP_TMP_PATH/$id"
touch "$FILE_WARP_TMP_PATH/$id/abs_dir"
touch "$FILE_WARP_TMP_PATH/$id/name"
. navdown2 "$start" "$mode"

abs_dir="$(cat "$FILE_WARP_TMP_PATH/$id/abs_dir")"
name="$(cat "$FILE_WARP_TMP_PATH/$id/name")"
abs_path="$abs_dir/$name"

if [[ $from_ide == 0 ]];then
  if [[ $TERM == "xterm-kitty" ]];then
    if [[ -f "$abs_path" ]];then
      if [[ $(file -b --mime-type workspaceFromTerminal) == "text"* ]];then
        openFileForEditing server$INDEX "$abs_path" &
      else
        open "$abs_path"
      fi
      if [[ "$mode" == normal ]];then
        cd "$abs_dir"
      fi
    else
      if [[ "$mode" == normal ]];then
        cd "$abs_dir"
      fi
    fi
  else
    if [[ -f "$abs_dir/$name" ]];then
      open "$abs_path"
      if [[ "$mode" == normal ]];then
        cd "$abs_dir"
      fi
    else
      if [[ "$mode" == normal ]];then
        cd "$abs_dir"
      fi
    fi
  fi
else
  if [[ -f "$abs_dir/$name" ]];then
    openFileForEditing "server$called_from_index" "$abs_dir/$name" normal
  else
    focusActiveEditor
  fi
fi
