#!/bin/bash

id="$1"

setQueryStr "$id" ""
abs_dir=`getAbsDir "$id"`
parent=$(dirname $abs_dir)
on_up=`getOnUp "$id"`

if [ ! -z "$on_up" ]; then
  eval "$on_up $parent"
fi
echo "$parent/" > /tmp/nav/path
#export abs_dir="$parent"
setAbsDir "$id" "$parent"
#echo "$parent" > /tmp/nav/abs_dir

#. navdown "$parent" "$on_enter" "$on_up" "$on_open" "$alt_open"
#reload "$parent"

