#!/bin/bash

id="$1"
setQueryStr "$id" ""
abs_dir=`getAbsDir "$id"`
parent=$(dirname $abs_dir)
on_up=`getOnUp "$id"`

if [ ! -z "$on_up" ]; then
  eval "$on_up $parent"
fi
setAbsDir "$id" "$parent"
if [[ -e $FILE_WARP_TMP_PATH/$id/index ]];then
  index="$(cat $FILE_WARP_TMP_PATH/$id/index)"
  if [[ $index == 0 ]];then
    setName "$id" ""
  else
    name="$(echo -n $(ls -GA --group-directories-first "$parent") | awk "{print \$$index}")"
    setName "$id" "$name"
  fi
fi

