#!/bin/bash

let curr_row=`cat /tmp/nav/row`
#echo $abs_dir >> /tmp/deb
count=$(ls $abs_dir | wc -w)
if [[ $curr_row -lt $count ]];then
  ((curr_row++))
  listing="\n $(ls $abs_dir)"
  listing_arr=($listing)
  echo ${listing_arr[$curr_row]} > /tmp/nav/cursor_at
  echo $curr_row > /tmp/nav/row
fi

