#!/bin/bash -e

set -o vi

if [[ -z "$id" ]]; then
  export MYPID=$(echo $$)
else
  export MYPID=$id
fi

path="$1"
mode="$2"


FZF_VAR=$(cat << B2
--ansi
--jump-labels=arstneiodhzxcvqwfpluyARSTNEIODHZXCVQWFPLUY
--layout=reverse
--tiebreak=begin,length
--bind=ctrl-e:down
--bind=ctrl-i:up
--bind=ctrl-a:backward-char
--bind=ctrl-t:forward-char
--bind=ctrl-r:preview-down
--bind=ctrl-s:preview-up
--bind=ctrl-q:preview-bottom
--bind=ctrl-y:preview-top
--bind=å:preview-half-page-down
--bind=é:preview-half-page-up
--bind=ä:backward-word
--bind=ã:forward-word
--bind=ctrl-x:backward-delete-char
--bind=đ:backward-kill-word
--bind=alt-/:kill-word
--bind=æ:clear-query
--bind=ctrl-alt-e:half-page-down
--bind=ctrl-alt-i:half-page-up
--bind=alt-e:last
--bind=insert:print-query
--bind=btab:replace-query
--bind=ctrl-a:toggle-all
--bind=ctrl-o:jump-accept
B2
)

export FZF_DEFAULT_OPTS="$FZF_VAR"
export FZF_DEFAULT_COMMAND="rg --follow --glob '' 2> $HOME/null"

#info $FILE_WARP_TMP_PATH
NVIM_LISTEN_ADDRESS="/tmp/vimnav$$" nvim0.6.1 -u /usr/bin/nav-enter.vim -c "let \$FILE_WARP_TMP_PATH='$FILE_WARP_TMP_PATH' | call ProjTreeFromTerminal('$path','$mode')"

#directory=$(getAbsDir $MYPID)
#name=$(getName $MYPID)
#path="$directory/$name"
#if [[ -f "$path" ]];then
  #open $path
#fi


#if [[ -e $FILE_WARP_TMP_PATH/$MYPID/killf ]]; then
  #rm -f $FILE_WARP_TMP_PATH/$MYPID/killc
#elif [[ -e $FILE_WARP_TMP_PATH/$MYPID/kill ]]; then
  #rm -f $FILE_WARP_TMP_PATH/$MYPID/kill
  #if [[ ! -z "$directory" ]]; then
    #owner=$(stat -c '%U' "$directory")
    #group=$(stat -c '%G' "$directory")
    #sudo chown $USER:me "$directory"
    #command cd "$directory"
    #sudo chown $owner:$group $directory
  #fi
  #if [[ -e $FILE_WARP_TMP_PATH/$MYPID/list_on_exit ]]; then
    #rm -f $FILE_WARP_TMP_PATH/$MYPID/list_on_exit
    #list2 .
  #fi
#else
  #if [[ "$MYPID" != 0 ]];then
    #id=$MYPID navdown2 "$1" "$2"
  #fi
#fi


#if [[ ! -e /tmp/tmp/no_custom_complete ]];then
  #customComplete
#fi

