#!/bin/bash -e
abs_dir=`getAbsDir "$MYPID"`

read -e -p 'new file:' filename
path="$abs_dir/$filename"
touch "$path"
echo "$path" > /tmp/output

if [[ -n "$(which getProjRootPath)" ]];then
  root="$(getProjRootPath "$abs_dir")/.git"
  git --git-dir "$root" add "$filename"
fi
#on_open=`getOnOpen "$id"`
#eval "$on_open $path"

