#!/bin/bash -e

path=`cat $FILE_WARP_TMP_PATH/path``cat $FILE_WARP_TMP_PATH/cursor_at`
#echo "$path" >> /tmp/deb
if [[ -d "$path" ]];then
  list2 "$path" | awk '{print $10, $11, $12}' > $FILE_WARP_TMP_PATH/preview
elif [[ -f "$path" ]];then
   -n 1000 $path > $FILE_WARP_TMP_PATH/preview
fi

