#!/bin/bash -e

server_name="$1"
endpoint_name="$2"
input_reg="$3"
output_reg="$4"

server_path="/dev/shm/servers/$server_name"
endpoint_path="$server_path/endpoints/$endpoint_name"

request_processor_idle_lock="$endpoint_path/idle_lock"

request_dir="$endpoint_path/input"
output_dir="$endpoint_path/output"
input_locks_dir="$endpoint_path/input_locks"
output_locks_dir="$endpoint_path/output_locks"

mkdir -p "$request_dir"
mkdir -p "$output_dir"
mkdir -p "$input_locks_dir"
mkdir -p "$output_locks_dir"

request_id="$(date +%Y_%m_%d_%H_%M_%S)_$PPID_$(uuidgen)"

echo "$output_reg" > "$output_dir/$request_id"
echo "$input_reg" > "$request_dir/$request_id"

releaseLock "$request_processor_idle_lock"
waitOnLock "$output_locks_dir/$request_id"

#if [[ -e "$output_dir/$request_id" ]];then
  #cat "$output_dir/$request_id" > "$output_reg"
#else
  #echo -n "null" > "$output_reg"
#fi
#rm -f "$output_dir/$request_id"

