#!/bin/bash -e

requests_path="$1"
locks_path="$2"
queue_lock_path="$3"
item="$4"

mkdir -p "$requests_path"
mkdir -p "$locks_path"


request_id="$(date +%Y_%m_%d_%H_%M_%S)_$PPID_$(uuidgen)"
request_path="$requests_path/$request_id"



#passValue()
#{
#param="$1"
#out_path="$2"

#mkdir -p $(dirname $out_path)

#if [[ -f "$param" ]];then
  #cat "$param" > "$out_path"
#else
  #echo "$param" > "$out_path"
#fi
#}

#passValue would make sense here if using queue for different usecase
#passValue "$item" "$request_path"


echo "$item" > "$request_path"

releaseLock "$queue_lock_path"
waitOnLock "$locks_path/$request_id"



