#!/bin/bash -e

var_base=${var_base:-/dev/shm/var}
mkdir -p "$var_base"
if [[ -e "$var_base/tmp_index" ]];then
  curr_val="$(cat "$var_base/tmp_index")"
else
  curr_val=0
fi

curr_val="$((curr_val+1))"
echo "$curr_val" > "$var_base/tmp_index"

var="$var_base/$curr_val"
/usr/bin/touch "$var"
echo "$var"
