#!/bin/bash -e

#IFS="\0"
#IFS="\n"

if [[ ! -e queue_pipe ]];then
  mkfifo queue_pipe
fi
mkfifo queue_lock

echo "" > queue_file
while true;do
#echo -n "$(cat queue_pipe)" >> queue_file
echo -ne "$(cat queue_pipe)\0" >> queue_file
#echo -ne "$IFS" >> queue_file
done
