#!/bin/bash

server_name="$1"
endpoint_name="$2"
endpoint="$3"

server_path="/dev/shm/servers/$server_name"
endpoint_path="$server_path/endpoints/$endpoint_name"
input_path="$endpoint_path/input"
output_path="$endpoint_path/output"
input_locks_dir="$endpoint_path/input_locks"
output_locks_dir="$endpoint_path/output_locks"

queue_path="$server_path/queues/$endpoint_name"
queue_lock_path="$endpoint_path/queue_lock"

rm -f $input_path/*

queueBroker "$queue_path" "$input_path" "$output_path" "$input_locks_dir" "$output_locks_dir" "$queue_lock_path" &
queue_id="$!"

trap "kill -9 $queue_id || x=pass" EXIT

log_dir="/mytmp/logs/ipc/$server_name/$endpoint_name"
mkdir -p "$log_dir"

info_log_path="$log_dir/info"
error_log_path="$log_dir/error"

touch "$info_log_path"
touch "$error_log_path"

while true;do
  input_reg="$(dequeue "$output_path" "$output_locks_dir" "$queue_lock_path")"
  io=$(mktmpVar)
#echo $endpoint > /tmp/tmp/logs/ipc/vim-com/sendCommandAsync/info
#echo $input_reg >> /tmp/tmp/logs/ipc/vim-com/sendCommandAsync/info
  if ! eval "$endpoint '$input_reg'" > "$io";then
    error_msg="error $(basename "$endpoint")! input: $(tr '\n' ' ' < "$input_reg")"
    if [[ -e "$io"  ]];then
      error_msg="$error_msg, message: $(cat "$io")"
    fi
    title="$server_name/$endpoint_name failed!" sendNotification "$error_msg"
    echo "$error_msg" >> "$error_log_path"
  else
    cat "$io" >> "$info_log_path"
  fi
  rm -f "$input_reg"
done
