#!/bin/bash

server_name="$1"
endpoint_name="$2"
endpoint="$3"

server_path="/dev/shm/servers/$server_name"
endpoint_path="$server_path/endpoints/$endpoint_name"

idle_lock="$endpoint_path/idle_lock"

request_dir="$endpoint_path/input"
output_dir="$endpoint_path/output"
input_locks_dir="$endpoint_path/input_locks"
output_locks_dir="$endpoint_path/output_locks"


mkdir -p "$request_dir"
mkdir -p "$output_dir"
mkdir -p "$input_locks_dir"
mkdir -p "$output_locks_dir"

log_dir="/mytmp/logs/ipc/$server_name/$endpoint_name"
mkdir -p "$log_dir"

info_log_path="$log_dir/info"
error_log_path="$log_dir/error"

touch "$info_log_path"
touch "$error_log_path"

while true;do
  # shellcheck disable=SC2045
  for request_id in $(ls "$request_dir");do
    in_request_path="$request_dir/$request_id"
    input_reg=$(cat "$in_request_path")
    rm -f "$in_request_path"

    output_reg="$(cat "$output_dir/$request_id")"
    rm -f "$output_dir/$request_id"
    io=$(mktmpVar)
    if ! eval "$endpoint '$input_reg' '$output_reg'" > "$io";then
      error_msg="error $(basename "$endpoint")! input: $(tr '\n' ' ' < "$input_reg")"
      if [[ -e "$io"  ]];then
        error_msg="$error_msg, message: $(cat "$io")"
      fi
      title="$server_name/$endpoint_name failed!" sendNotification "$error_msg"
      echo "$error_msg" >> "$error_log_path"
    else
      cat "$io" >> "$info_log_path"
    fi

    releaseLock "$output_locks_dir/$request_id"
  done
  if [[ -z $(ls "$request_dir") ]];then
    #echo "waiting for requests"
    waitOnLock "$idle_lock"
  fi
done
